/**
 * Componentes visuales compartidos del panel cliente: Safe Area, tarjetas y estados de consulta. Reciben contenido y acciones por props, usan ThemeContext y no generan registros de negocio.
 */
import { useState,type PropsWithChildren,type ReactNode } from 'react';
import { Image,Pressable,ScrollView,StyleSheet,View,KeyboardAvoidingView,Platform } from 'react-native';
import { SafeAreaView,useSafeAreaInsets } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { useAuth } from '../../hooks/useAuth';
import { roleHome } from '../../utils/role-home';
import { useTheme } from '../../hooks/useTheme';
import { AppText } from '../ui/AppText';
import { AppButton } from '../ui/AppButton';
import { FormNotice } from '../ui/FormNotice';
import { LoadingIndicator } from '../ui/LoadingIndicator';
export type IconName=React.ComponentProps<typeof Ionicons>['name'];
export function PetCareScreen({children}:PropsWithChildren){const {colors}=useTheme();const insets=useSafeAreaInsets();return <SafeAreaView edges={['top','left','right']} style={{flex:1,backgroundColor:colors.background}}><KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={[styles.screen,{paddingBottom:32+insets.bottom}]}><View pointerEvents="none" accessible={false} style={styles.decoration}><Ionicons name="paw" size={180} color={colors.muted}/></View>{children}</ScrollView></KeyboardAvoidingView></SafeAreaView>;}
export function PetCareHeader({title,subtitle,back=false,right}: {title:string;subtitle?:string;back?:boolean;right?:ReactNode}){const {colors}=useTheme();const {user}=useAuth();return <View style={styles.header}>{back&&<PetCareIconButton icon="arrow-back" label="Volver" onPress={()=>router.canGoBack()?router.back():router.replace(roleHome(user))}/>}<View style={styles.flex}><Image source={require('../../assets/petcare-logo.png')} style={[styles.logo,{tintColor:colors.text}]} resizeMode="contain" accessibilityLabel="PetCare"/><AppText variant="title" style={styles.title}>{title}</AppText>{subtitle&&<AppText muted>{subtitle}</AppText>}</View>{right}</View>;}
export function PetCareCard({children}:PropsWithChildren){const {colors}=useTheme();return <View style={[styles.card,{backgroundColor:colors.surface,borderColor:colors.border}]}>{children}</View>;}
export function PetCareBadge({label}: {label:string}){const {colors}=useTheme();return <View style={[styles.badge,{backgroundColor:colors.accent}]}><AppText variant="caption">{label}</AppText></View>;}
export function PetCareSection({title,children}:PropsWithChildren<{title:string}>){return <View style={styles.section}><AppText variant="subtitle">{title}</AppText>{children}</View>;}
export function PetCareIconButton({icon,label,onPress}:{icon:IconName;label:string;onPress:()=>void}){const {colors}=useTheme();return <Pressable accessibilityRole="button" accessibilityLabel={label} onPress={onPress} style={[styles.iconButton,{backgroundColor:colors.accent}]}><Ionicons name={icon} size={23} color={colors.text}/></Pressable>;}
export function PetCareEmptyState({title,message,icon='paw-outline',action,label}: {title:string;message?:string;icon?:IconName;action?:()=>void;label?:string}){const {colors}=useTheme();return <PetCareCard><View style={styles.empty}><View style={[styles.emptyIcon,{backgroundColor:colors.accent}]}><Ionicons name={icon} size={38} color={colors.primary}/></View><AppText variant="subtitle" style={styles.center}>{title}</AppText>{message&&<AppText muted style={styles.center}>{message}</AppText>}{action&&label&&<AppButton label={label} onPress={action}/>}</View></PetCareCard>;}
export function QueryState({loading,error,reload}:{loading:boolean;error:string|null;reload:()=>void}){return <>{loading&&<LoadingIndicator label="Consultando PetCare…"/>}{error&&<PetCareCard><FormNotice error message={error}/><AppButton label="Reintentar" onPress={reload}/></PetCareCard>}</>;}
export function PetCareAction({title,icon,onPress}:{title:string;icon:IconName;onPress:()=>void}){const {colors}=useTheme();return <Pressable accessibilityRole="button" onPress={onPress} style={[styles.action,{backgroundColor:colors.surface,borderColor:colors.border}]}><Ionicons name={icon} color={colors.primary} size={24}/><AppText style={styles.flex}>{title}</AppText><Ionicons name="chevron-forward" color={colors.muted} size={20}/></Pressable>;}
export function PetImage({uri}: {uri:string|null}){const {colors}=useTheme();const [failed,setFailed]=useState<string|null>(null);return <View style={[styles.photo,{backgroundColor:colors.accent}]}>{uri&&failed!==uri?<Image source={{uri}} onError={()=>setFailed(uri)} style={styles.photo} resizeMode="cover" accessibilityLabel="Foto registrada"/>:<Ionicons name="paw-outline" size={36} color={colors.muted}/>}</View>;}
export const money=(cents:number)=>new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS'}).format(cents/100);
export const dateTime=(value:string)=>new Date(value).toLocaleString('es-AR',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit',timeZone:'America/Argentina/Buenos_Aires'});
// Etiquetas traducen códigos persistidos; no crean estados ni registros.
export const statusLabel=(value:string)=>({REQUESTED:'Solicitado',CONFIRMED:'Confirmado',IN_PROGRESS:'En atención',COMPLETED:'Finalizado',CANCELLED:'Cancelado',PLACED:'Solicitada',PROCESSING:'En preparación',READY:'Lista para retirar'}[value]??value);
const styles=StyleSheet.create({screen:{overflow:'hidden',flexGrow:1,width:'100%',maxWidth:600,alignSelf:'center',padding:20,paddingBottom:32,gap:22},decoration:{position:'absolute',top:120,right:-30,opacity:0.05},header:{flexDirection:'row',alignItems:'center',gap:12},flex:{flex:1,minWidth:0},logo:{width:90,height:30,alignSelf:'flex-start'},title:{fontSize:29,lineHeight:35,marginTop:8},card:{padding:18,borderRadius:24,borderWidth:1,gap:12},badge:{paddingHorizontal:12,paddingVertical:5,borderRadius:12,alignSelf:'flex-start'},section:{gap:14},iconButton:{width:48,height:48,borderRadius:18,alignItems:'center',justifyContent:'center'},empty:{alignItems:'center',gap:14,paddingVertical:12,width:'100%'},emptyIcon:{width:76,height:76,borderRadius:28,alignItems:'center',justifyContent:'center'},center:{textAlign:'center'},action:{minHeight:66,padding:16,borderRadius:20,borderWidth:1,flexDirection:'row',alignItems:'center',gap:14},photo:{width:80,height:80,borderRadius:24,alignItems:'center',justifyContent:'center',overflow:'hidden'}});
