-- Adopción documental del esquema clínico ya existente.
-- Este archivo NO contiene SQL ejecutable de negocio ni recrea tablas.
-- clinic-reconcile.ts valida tablas, columnas, claves foráneas, índices y datos
-- antes de registrar esta versión. El único DDL condicional permitido es:
--   1. Crear veterinarian_history(veterinarian_id) si falta un índice no único
--      cuyo primer campo sea veterinarian_id.
--   2. Eliminar veterinarian_start únicamente si es UNIQUE exacto sobre
--      (veterinarian_id, starts_at), ninguna FK lo requiere, la FK veterinaria
--      esperada existe, los datos pasan el preflight y ya hay índice de soporte.
-- Los índices equivalentes uq_professional_active_start,
-- uq_client_occupied_slot e idx_client_slot_history se conservan por nombre.
-- 001_connected_clinic.sql queda expresamente sin ejecutar y sin registrar.
