/** Configuración administrable: todos los catálogos y asignaciones viven en MySQL. */
import type { AuthUser } from '../types/auth';
import * as db from './clinic.repository';
import * as v from '../validators/clinic.validator';
import { assertAdminPermission,forbidden } from '../utils/admin-authorization';
const entities={services:{table:'client_services',permission:'services.manage',fields:{name:'name',description:'description',specialtyId:'specialty_id',typeId:'professional_type_id',durationMinutes:'duration_minutes',priceCents:'price_cents',requirements:'requirements',isActive:'is_active'}},categories:{table:'client_product_categories',permission:'categories.manage',fields:{name:'name',isActive:'is_active'}},products:{table:'client_products',permission:'products.update',fields:{name:'name',description:'description',categoryId:'category_id',imageUrl:'image_url',priceCents:'price_cents',stock:'stock',isActive:'is_active',isFeatured:'is_featured',requiresPrescription:'requires_prescription',speciesId:'species_id'}},promotions:{table:'client_promotions',permission:'promotions.manage',fields:{name:'name',productId:'product_id',priceCents:'price_cents',startsAt:'starts_at',endsAt:'ends_at',isActive:'is_active'}},types:{table:'professional_types',permission:'professional_types.manage',fields:{name:'name',roleId:'role_id',isClinical:'is_clinical'}},specialties:{table:'specialties',permission:'specialties.manage',fields:{name:'name',isActive:'is_active'}}} as const;
export type Entity=keyof typeof entities;
export function entity(name:string):Entity {if(!Object.hasOwn(entities,name))v.invalid();return name as Entity;}
export async function list(actor:AuthUser,name:Entity,query:Record<string,unknown>={}) {const config=entities[name];assertAdminPermission(actor,config.permission);const fields=Object.entries(config.fields).map(([alias,column])=>`${column} AS ${alias}`).join(',');const search=v.text(query.search,100,true)??'';return db.rows(`SELECT id,${fields} ${name==='products'?',reserved_stock AS reservedStock':''} FROM ${config.table} WHERE name LIKE ? ORDER BY name LIMIT 100 OFFSET ${(v.queryPage(query)-1)*100}`,[`%${search}%`]);}
export async function save(actor:AuthUser,name:Entity,id:string|undefined,value:unknown) {const config=entities[name];const fields:Record<string,string>=config.fields;const body=v.body(value,Object.keys(fields));const names=Object.keys(body);if(!names.length)v.invalid();if(!id&&!body.name)v.invalid('Ingresá un nombre.');
 const converted:db.Data={};for(const key of names){const value=body[key];converted[key]=key==='name'?v.text(value,name==='products'?200:100):key==='imageUrl'?v.imageUrl(value):key.endsWith('Id')?v.optionalId(value):key.startsWith('is')||key==='requiresPrescription'?v.bool(value):key.endsWith('At')?v.instant(value):['stock','priceCents','durationMinutes'].includes(key)?(key==='priceCents'&&value===null?null:v.integer(value,key==='durationMinutes'?5:0,key==='durationMinutes'?480:100000000)):v.text(value,10000,true);}
 return db.transaction(actor,async(c,fresh)=>{assertAdminPermission(fresh,config.permission);if(name==='products'){if(!id)assertAdminPermission(fresh,'products.create','products.update_price','products.update_stock');if(body.priceCents!==undefined)assertAdminPermission(fresh,'products.update_price');if(body.stock!==undefined)assertAdminPermission(fresh,'products.update_stock');if(!id&&(body.priceCents===undefined||body.stock===undefined))v.invalid('Indicá precio informativo y stock.');if(id){const current=await db.one('SELECT reserved_stock AS reservedStock FROM client_products WHERE id=? FOR UPDATE',[id],c);if(body.stock!==undefined&&Number(body.stock)<Number(current.reservedStock))v.invalid('El stock físico no puede ser menor al reservado.');}}
  if(id)await db.one(`SELECT id FROM ${config.table} WHERE id=? FOR UPDATE`,[id],c);
  if(name==='services'){if((!id||body.typeId!==undefined)&&!converted.typeId)v.invalid('Seleccioná el tipo profesional.');if(converted.typeId){const type=await db.one('SELECT id,is_clinical AS isClinical FROM professional_types WHERE id=?',[converted.typeId],c);if(!type.isClinical&&converted.specialtyId)v.invalid('Un servicio no clínico no requiere especialidad veterinaria.');}if(converted.specialtyId)await db.one('SELECT id FROM specialties WHERE id=? AND is_active=1',[converted.specialtyId],c);}
  if(name==='types'){if(!id){const role=await db.one('SELECT code FROM roles WHERE id=?',[converted.roleId],c);if(!['VETERINARIAN','GROOMER'].includes(String(role.code)))v.invalid('Este rol no es profesional.');if(Boolean(converted.isClinical)!==(role.code==='VETERINARIAN'))v.invalid('El acceso clínico corresponde exclusivamente al rol veterinario.');}else if(body.roleId!==undefined||body.isClinical!==undefined)v.invalid('No se cambia el rol ni acceso clínico de un tipo utilizado.');}
  if(name==='promotions'&&converted.startsAt&&converted.endsAt&&String(converted.endsAt)<=String(converted.startsAt))v.invalid('La promoción debe terminar después de comenzar.');
  if(id)await c.execute(`UPDATE ${config.table} SET ${names.map(key=>`${fields[key]}=?`).join(',')} WHERE id=?`,[...names.map(key=>converted[key]),id]);
  else await c.execute(`INSERT INTO ${config.table}(${names.map(key=>fields[key]).join(',')}) VALUES (${names.map(()=>'?').join(',')})`,names.map(key=>converted[key]));return {saved:true};
 });
}
export async function assignServices(actor:AuthUser,id:string,value:unknown) {const body=v.body(value,['serviceIds']);if(!Array.isArray(body.serviceIds)||body.serviceIds.length>100)v.invalid();const ids=[...new Set(body.serviceIds.map(v.id))];return db.transaction(actor,async(c,fresh)=>{assertAdminPermission(fresh,'professionals.manage');const p=await db.one('SELECT u.id,pt.id AS typeId,vt.id AS veterinarianId FROM users u JOIN professional_types pt ON pt.id=COALESCE((SELECT chosen.id FROM professional_types chosen WHERE chosen.id=u.professional_type_id AND chosen.role_id=u.role_id),(SELECT default_role.professional_type_id FROM roles default_role WHERE default_role.id=u.role_id)) LEFT JOIN veterinarians vt ON vt.user_id=u.id WHERE u.id=? FOR UPDATE',[id],c);
 for(const serviceId of ids){const s=await db.one('SELECT professional_type_id AS typeId,specialty_id AS specialtyId FROM client_services WHERE id=?',[serviceId],c);if(s.typeId!==p.typeId)v.invalid('El servicio no corresponde al tipo profesional.');if(s.specialtyId)await db.one('SELECT specialty_id AS id FROM veterinarian_specialties WHERE veterinarian_id=? AND specialty_id=?',[p.veterinarianId,s.specialtyId],c);}
 await c.execute('DELETE FROM professional_services WHERE user_id=?',[id]);for(const serviceId of ids)await c.execute('INSERT INTO professional_services(user_id,service_id) VALUES (?,?)',[id,serviceId]);return {saved:true};});}
export async function availability(actor:AuthUser,query:Record<string,unknown>) {assertAdminPermission(actor,'schedule.manage');const id=v.id(query.professionalId);return {slots:await db.rows('SELECT id,service_id AS serviceId,starts_at AS startsAt,ends_at AS endsAt,is_active AS isActive FROM client_appointment_slots WHERE professional_user_id=? ORDER BY starts_at DESC LIMIT 300',[id]),blocks:await db.rows('SELECT id,starts_at AS startsAt,ends_at AS endsAt,reason,is_active AS isActive FROM professional_blocks WHERE user_id=? ORDER BY starts_at DESC LIMIT 100',[id])};}
export async function saveAvailability(actor:AuthUser,value:unknown) {const body=v.body(value,['professionalId','serviceId','startsAt','endsAt','block','reason']);const professionalId=v.id(body.professionalId),starts=v.instant(body.startsAt),ends=v.instant(body.endsAt);if(ends<=starts||starts<new Date().toISOString().slice(0,19).replace('T',' '))v.invalid('Revisá el intervalo futuro de atención.');const block=body.block===true;
 return db.transaction(actor,async(c,fresh)=>{assertAdminPermission(fresh,'schedule.manage');const professional=await db.one('SELECT u.id,pt.id AS typeId FROM users u JOIN professional_types pt ON pt.id=COALESCE((SELECT chosen.id FROM professional_types chosen WHERE chosen.id=u.professional_type_id AND chosen.role_id=u.role_id),(SELECT default_role.professional_type_id FROM roles default_role WHERE default_role.id=u.role_id)) WHERE u.id=? AND u.is_active=1 FOR UPDATE',[professionalId],c);
  const overlaps=await db.rows(`SELECT s.id FROM client_appointment_slots s WHERE s.professional_user_id=? AND s.is_active=1 AND s.starts_at<? AND s.ends_at>? ${block?"AND EXISTS(SELECT 1 FROM client_appointments a WHERE a.slot_id=s.id AND a.status<>'CANCELLED')":''}`,[professionalId,ends,starts],c);if(overlaps.length)v.invalid('El intervalo se superpone con un horario o turno existente.');
  if(block){await c.execute('INSERT INTO professional_blocks(user_id,starts_at,ends_at,reason) VALUES (?,?,?,?)',[professionalId,starts,ends,v.text(body.reason,200)!]);return {saved:true};}
  const serviceId=v.id(body.serviceId);const service=await db.one('SELECT s.professional_type_id AS typeId,s.duration_minutes AS durationMinutes,s.specialty_id AS specialtyId FROM client_services s JOIN professional_services ps ON ps.service_id=s.id WHERE s.id=? AND ps.user_id=? AND s.is_active=1',[serviceId,professionalId],c);if(service.typeId!==professional.typeId)v.invalid('El servicio no corresponde al profesional.');
  if(service.specialtyId)await db.one('SELECT vs.specialty_id AS id FROM veterinarian_specialties vs JOIN veterinarians vt ON vt.id=vs.veterinarian_id JOIN specialties sp ON sp.id=vs.specialty_id WHERE vt.user_id=? AND vs.specialty_id=? AND sp.is_active=1',[professionalId,service.specialtyId],c);
  const blocks=await db.rows('SELECT id FROM professional_blocks WHERE user_id=? AND is_active=1 AND starts_at<? AND ends_at>?',[professionalId,ends,starts],c);if(blocks.length)v.invalid('El profesional tiene un bloqueo en ese intervalo.');
  const duration=Number(service.durationMinutes)*60000;const startMs=Date.parse(starts.replace(' ','T')+'Z'),endMs=Date.parse(ends.replace(' ','T')+'Z');if((endMs-startMs)%duration!==0||(endMs-startMs)/duration>100)v.invalid('El bloque debe contener hasta 100 turnos completos de la duración del servicio.');
  for(let time=startMs;time+duration<=endMs;time+=duration){const format=(ms:number)=>new Date(ms).toISOString().slice(0,19).replace('T',' ');await c.execute('INSERT INTO client_appointment_slots(service_id,professional_user_id,professional_type_id,veterinarian_id,starts_at,ends_at) VALUES (?,?,?,(SELECT id FROM veterinarians WHERE user_id=?),?,?)',[serviceId,professionalId,service.typeId,professionalId,format(time),format(time+duration)]);}return {saved:true};
 });}
export async function disableAvailability(actor:AuthUser,kind:string,id:string) {if(!['slot','block'].includes(kind))v.invalid();return db.transaction(actor,async(c,fresh)=>{assertAdminPermission(fresh,'schedule.manage');const table=kind==='slot'?'client_appointment_slots':'professional_blocks';const row=await db.one(`SELECT ${kind==='slot'?'professional_user_id':'user_id'} AS professionalId FROM ${table} WHERE id=?`,[id],c);await c.execute('SELECT id FROM users WHERE id=? FOR UPDATE',[row.professionalId]);if(kind==='slot'&&(await db.rows("SELECT id FROM client_appointments WHERE slot_id=? AND status<>'CANCELLED'",[id],c)).length)v.invalid('Reprogramá o cancelá el turno antes de desactivar el horario.');await c.execute(`UPDATE ${table} SET is_active=0 WHERE id=?`,[id]);return {saved:true};});}
export function administrative(actor:AuthUser){if(!['ADMIN','SUPER_ADMIN'].includes(actor.role))forbidden();}

export async function assignType(actor:AuthUser,id:string,value:unknown) {const body=v.body(value,['typeId']);const typeId=v.id(body.typeId);return db.transaction(actor,async(c,fresh)=>{assertAdminPermission(fresh,'professionals.manage');const user=await db.one('SELECT id,role_id AS roleId FROM users WHERE id=? FOR UPDATE',[id],c);const type=await db.one('SELECT id,role_id AS roleId FROM professional_types WHERE id=?',[typeId],c);if(user.roleId!==type.roleId)v.invalid('El tipo debe corresponder al rol profesional de la cuenta.');
 const occupied=await db.rows("SELECT a.id FROM client_appointments a JOIN client_appointment_slots s ON s.id=a.slot_id WHERE s.professional_user_id=? AND a.status NOT IN ('CANCELLED','COMPLETED') AND s.ends_at>UTC_TIMESTAMP()",[id],c);if(occupied.length)v.invalid('Reprogramá los turnos vigentes antes de cambiar el tipo profesional.');
 await c.execute('UPDATE users SET professional_type_id=? WHERE id=?',[typeId,id]);await c.execute('DELETE ps FROM professional_services ps JOIN client_services s ON s.id=ps.service_id WHERE ps.user_id=? AND s.professional_type_id<>?',[id,typeId]);return {saved:true};});}
