/**
 * Pantalla de detalle de producto para CLIENT autenticado. Usa los hooks y servicios autenticados de su módulo (/client o /clinic según la operación); no debe decidir ownership ni privilegios a partir de parámetros locales.
 */
import { useCallback,useState } from 'react';
import { router,useLocalSearchParams } from 'expo-router';
import { useClient } from '../../../hooks/useClient';
import { useClinic } from '../../../hooks/useClinic';
import { useClientQuery } from '../../../hooks/useClientQuery';
import { useFeedback } from '../../../contexts/FeedbackContext';
import { PetCareScreen,PetCareHeader,PetCareCard,PetCareBadge,PetImage,QueryState,money } from '../../../components/client/PetCareUI';
import { AppText } from '../../../components/ui/AppText';
import { AppButton } from '../../../components/ui/AppButton';
import { AppInput } from '../../../components/forms/AppInput';
import { SelectionRow } from '../../../components/ui/SelectionRow';
import { FormNotice } from '../../../components/ui/FormNotice';
import { ConfirmModal } from '../../../components/ui/ConfirmModal';
export default function ProductDetail(){const {id}=useLocalSearchParams<{id:string}>();const api=useClient(),clinic=useClinic();const query=useClientQuery(useCallback(()=>api.product(id),[api,id]));const pets=useClientQuery(api.pets);const [quantity,setQuantity]=useState('1'),[petId,setPet]=useState(''),[prescriptionId,setPrescription]=useState(''),[confirm,setConfirm]=useState(false),[error,setError]=useState<string|null>(null);const {showToast}=useFeedback();const prescriptions=useClientQuery(useCallback(()=>petId?api.clinical('prescriptions',petId):Promise.resolve(null),[api,petId]));
 return <PetCareScreen><PetCareHeader title={query.data?.name??'Producto'} back/><QueryState {...query}/>{query.data&&<><PetCareCard><PetImage uri={query.data.imageUrl}/>{query.data.category&&<PetCareBadge label={query.data.category}/>}<AppText variant="subtitle">Precio informativo: {money(query.data.priceCents)}</AppText>{query.data.description&&<AppText>{query.data.description}</AppText>}<AppText>{query.data.stock>0?`${query.data.stock} disponibles para reservar`:'Sin unidades disponibles'}</AppText><AppText muted>Reserva para retirar en la veterinaria. PetCare no procesa pagos.</AppText><AppInput label="Cantidad" keyboardType="number-pad" value={quantity} onChangeText={setQuantity}/></PetCareCard>{(query.data.requiresPrescription||query.data.speciesId)&&<><QueryState {...pets}/><PetCareCard><AppText variant="subtitle">Mascota</AppText>{pets.data?.filter(p=>!query.data?.speciesId||p.speciesId===query.data.speciesId).map(p=><SelectionRow key={p.id} label={p.name} checked={petId===p.id} onPress={()=>{setPet(p.id);setPrescription('');}}/>)}</PetCareCard></>}{query.data.requiresPrescription&&<><QueryState {...prescriptions}/><PetCareCard><AppText variant="subtitle">Receta vigente</AppText>{prescriptions.data?.filter(r=>r.productId===id&&r.isValid).map(r=><SelectionRow key={r.id} label={r.title} checked={prescriptionId===r.id} onPress={()=>setPrescription(r.id)}/>)}<AppText muted>El backend comprueba que la receta corresponde a esta mascota y producto y que el veterinario definió su vigencia.</AppText></PetCareCard></>}<FormNotice error message={error}/><AppButton label="Confirmar reserva" disabled={query.data.stock<=0} onPress={()=>{if(!/^[1-9]\d?$/.test(quantity)||Number(quantity)>query.data!.stock||(query.data!.requiresPrescription&&(!petId||!prescriptionId))||(query.data!.speciesId&&!petId)){setError('Revisá cantidad, mascota y receta cuando corresponda.');return;}setError(null);setConfirm(true);}}/><AppButton label="Mis reservas" variant="secondary" onPress={()=>router.push('/client/orders')}/></>}<ConfirmModal visible={confirm} title="Confirmar reserva" message="Se reservarán las unidades disponibles. La clínica gestionará la solicitud para retiro. No se realiza un pago." confirmLabel="Reservar" onCancel={()=>setConfirm(false)} onConfirm={async()=>{const result=await clinic.reserve({productId:id,quantity:Number(quantity),petId:petId||null,prescriptionId:prescriptionId||null,requestKey:query.data?.reservationKey});setConfirm(false);showToast('Reserva solicitada','success');router.replace({pathname:'/client/reservation' as never,params:{id:result.id}});}}/></PetCareScreen>;
}
