import { useCallback,useState } from 'react';
import { router } from 'expo-router';
import { useClinic } from '../../hooks/useClinic';
import { useAuth } from '../../hooks/useAuth';
import { useClientQuery } from '../../hooks/useClientQuery';
import { PetCareScreen,PetCareHeader,PetCareCard,PetCareEmptyState,QueryState,statusLabel } from '../client/PetCareUI';
import { AppText } from '../ui/AppText';
import { AppButton } from '../ui/AppButton';
import { AppInput } from '../forms/AppInput';
import { SelectionRow } from '../ui/SelectionRow';
import { clinicDateTime } from '../../utils/clinic-date';
export function AgendaScreen(){const api=useClinic();const {user,hasPermission}=useAuth();const base=user?.role==='VETERINARIAN'?'/vet':user?.role==='GROOMER'?'/professional':user?.role==='SECRETARY'?'/secretary':'/admin';const [period,setPeriod]=useState('upcoming');const [filters,setFilters]=useState<Record<string,string>>({});const [date,setDate]=useState('');const catalog=useClientQuery(api.catalog);const query=useClientQuery(useCallback(()=>api.appointments(filters),[api,filters]));const [page,setPage]=useState(1);
 const today=new Date().toLocaleDateString('sv-SE',{timeZone:'America/Argentina/Buenos_Aires'});const filtered=query.data?.filter(a=>{const day=new Date(String(a.startsAt)).toLocaleDateString('sv-SE',{timeZone:'America/Argentina/Buenos_Aires'});return period==='all'||(period==='today'?day===today:period==='past'?day<today:day>=today);});
 return <PetCareScreen><PetCareHeader title="Agenda y turnos" subtitle="Horarios compartidos con la clínica" back/><PetCareCard>{[['today','Hoy'],['upcoming','Próximos'],['past','Anteriores'],['all','Todos']].map(([key,label])=><SelectionRow radio key={key} label={label} checked={period===key} onPress={()=>setPeriod(key)}/>)}<AppInput label="Fecha DD/MM/AAAA" value={date} onChangeText={setDate}/><AppButton label="Filtrar fecha" onPress={()=>{const m=/^(\d{2})\/(\d{2})\/(\d{4})$/.exec(date);setFilters(f=>({...f,date:m?`${m[3]}-${m[2]}-${m[1]}`:''}));}}/>{['','REQUESTED','CONFIRMED','IN_PROGRESS','COMPLETED','CANCELLED'].map(status=><SelectionRow key={status} label={status?statusLabel(status):'Todos los estados'} checked={(filters.status??'')===status} onPress={()=>setFilters(f=>({...f,status}))}/>)}</PetCareCard>
 <QueryState {...catalog}/>{catalog.data&&<PetCareCard><AppText variant="subtitle">Servicio</AppText><SelectionRow label="Todos" checked={!filters.serviceId} onPress={()=>setFilters(f=>({...f,serviceId:''}))}/>{catalog.data.services.map(s=><SelectionRow key={s.id} label={String(s.name)} checked={filters.serviceId===s.id} onPress={()=>setFilters(f=>({...f,serviceId:s.id}))}/>)}{hasPermission('appointments.view_all')&&<><AppText variant="subtitle">Profesional</AppText><SelectionRow label="Todos" checked={!filters.professionalId} onPress={()=>setFilters(f=>({...f,professionalId:''}))}/>{catalog.data.professionals.map(p=><SelectionRow key={p.id} label={String(p.name)} checked={filters.professionalId===p.id} onPress={()=>setFilters(f=>({...f,professionalId:p.id}))}/>)}</>}</PetCareCard>}
 <QueryState {...query}/>{filtered&&(filtered.length?filtered.map(a=><PetCareCard key={a.id}><AppText variant="subtitle">{String(a.petName)} · {String(a.service)}</AppText><AppText>{clinicDateTime(String(a.startsAt))}</AppText><AppText>{String(a.veterinarian)} · {statusLabel(String(a.status))}</AppText><AppButton label="Ver turno" variant="secondary" onPress={()=>router.push({pathname:`${base}/appointment` as never,params:{id:a.id}})}/></PetCareCard>):<PetCareEmptyState title="No hay turnos en esta consulta" icon="calendar-outline"/>)}<AppButton label="Página anterior" disabled={page===1} onPress={()=>{setPage(p=>p-1);setFilters(f=>({...f,page:String(page-1)}));}}/><AppButton label="Siguiente página" disabled={!query.data||query.data.length<200} onPress={()=>{setPage(p=>p+1);setFilters(f=>({...f,page:String(page+1)}));}}/></PetCareScreen>;
}
