import { useCallback,useState } from 'react';
import { useLocalSearchParams } from 'expo-router';
import { useClinic } from '../../hooks/useClinic';
import { useAdmin } from '../../hooks/useAdmin';
import { useAuth } from '../../hooks/useAuth';
import { useClientQuery } from '../../hooks/useClientQuery';
import { PetCareScreen,PetCareHeader,PetCareCard,PetCareEmptyState,QueryState } from '../client/PetCareUI';
import { AppText } from '../ui/AppText';
import { AppButton } from '../ui/AppButton';
import { AppInput } from '../forms/AppInput';
import { FormNotice } from '../ui/FormNotice';
import { SelectionRow } from '../ui/SelectionRow';
import { ConfirmModal } from '../ui/ConfirmModal';
import { useFeedback } from '../../contexts/FeedbackContext';
import { clinicInstant,clinicDateTime } from '../../utils/clinic-date';
import type { ClinicRow } from '../../types/clinic';
type Field={key:string;label:string;type:'text'|'number'|'bool'|'select'|'date';catalog?:string;optional?:boolean;permission?:string};
// Metadatos del formulario: no son catálogos funcionales ni conceden permisos.
const forms:Record<string,{title:string;permission:string;fields:Field[]}>={
 services:{title:'Servicios',permission:'services.manage',fields:[{key:'name',label:'Nombre',type:'text'},{key:'description',label:'Descripción',type:'text',optional:true},{key:'typeId',label:'Tipo profesional',type:'select',catalog:'types'},{key:'specialtyId',label:'Especialidad requerida',type:'select',catalog:'specialties',optional:true},{key:'durationMinutes',label:'Duración en minutos',type:'number'},{key:'priceCents',label:'Precio informativo en centavos',type:'number',optional:true},{key:'requirements',label:'Requisitos',type:'text',optional:true},{key:'isActive',label:'Activo',type:'bool'}]},
 categories:{title:'Categorías',permission:'categories.manage',fields:[{key:'name',label:'Nombre',type:'text'},{key:'isActive',label:'Activa',type:'bool'}]},
 products:{title:'Productos y stock',permission:'products.update',fields:[{key:'name',label:'Nombre',type:'text'},{key:'description',label:'Descripción',type:'text',optional:true},{key:'categoryId',label:'Categoría',type:'select',catalog:'categories',optional:true},{key:'imageUrl',label:'URL HTTPS de imagen del producto',type:'text',optional:true},{key:'priceCents',label:'Precio informativo en centavos',type:'number',permission:'products.update_price'},{key:'stock',label:'Stock físico',type:'number',permission:'products.update_stock'},{key:'speciesId',label:'Especie aplicable',type:'select',catalog:'species',optional:true},{key:'requiresPrescription',label:'Requiere receta vigente',type:'bool'},{key:'isFeatured',label:'Destacado',type:'bool'},{key:'isActive',label:'Activo',type:'bool'}]},
 promotions:{title:'Promociones informativas',permission:'promotions.manage',fields:[{key:'name',label:'Nombre',type:'text'},{key:'productId',label:'Producto',type:'select',catalog:'products'},{key:'priceCents',label:'Precio informativo en centavos',type:'number'},{key:'startsAt',label:'Inicio DD/MM/AAAA HH:mm',type:'date'},{key:'endsAt',label:'Fin DD/MM/AAAA HH:mm',type:'date'},{key:'isActive',label:'Activa',type:'bool'}]},
 specialties:{title:'Especialidades',permission:'specialties.manage',fields:[{key:'name',label:'Nombre',type:'text'},{key:'isActive',label:'Activa',type:'bool'}]},
 types:{title:'Tipos profesionales',permission:'professional_types.manage',fields:[{key:'name',label:'Nombre',type:'text'},{key:'roleId',label:'Rol profesional',type:'select',catalog:'roles'},{key:'isClinical',label:'Capacidad clínica (solo Veterinario)',type:'bool'}]},
};
export function CatalogScreen(){const {kind}=useLocalSearchParams<{kind:string}>();const form=forms[kind];const {hasPermission}=useAuth();const api=useClinic();const admin=useAdmin();const [search,setSearch]=useState(''),[submitted,setSubmitted]=useState(''),[page,setPage]=useState(1);const [editing,setEditing]=useState<ClinicRow|null>(null);const [values,setValues]=useState<Record<string,string|boolean>>({});const [error,setError]=useState<string|null>(null),[confirm,setConfirm]=useState(false);const {showToast}=useFeedback();const query=useClientQuery(useCallback(()=>form&&hasPermission(form.permission)?api.adminList(kind,{search:submitted,page:String(page)}):Promise.resolve(null),[api,kind,form,hasPermission,submitted,page]));const catalog=useClientQuery(api.catalog);const roles=useClientQuery(useCallback(()=>kind==='types'?admin.catalog():Promise.resolve(null),[kind,admin]));const products=useClientQuery(useCallback(()=>kind==='promotions'?api.adminList('products'):Promise.resolve(null),[kind,api]));
 if(!form||!hasPermission(form.permission))return <PetCareScreen><PetCareHeader title="Acceso restringido" back/><FormNotice error message="No tenés permiso para este módulo."/></PetCareScreen>;
 function begin(row?:ClinicRow){setEditing(row??{id:''});setValues(Object.fromEntries(form.fields.map(f=>[f.key,f.type==='bool'?Boolean(row?.[f.key]):f.type==='date'&&row?.[f.key]?clinicDateTime(String(row[f.key])).replace(',',''):String(row?.[f.key]??'')])));setError(null);}
 const options=(name?:string):{id:string;name:string}[]=>name==='roles'?(roles.data?.roles.filter(r=>['VETERINARIAN','GROOMER'].includes(r.code)).map(r=>({id:r.id,name:r.name}))??[]):name==='products'?products.data?.map(r=>({id:r.id,name:String(r.name)}))??[]:((catalog.data as unknown as Record<string,ClinicRow[]>|null)?.[name??'']??[]).map(r=>({id:r.id,name:String(r.name)}));
 function payload(){const result:Record<string,unknown>={};for(const field of form.fields){if(field.permission&&!hasPermission(field.permission))continue;if(kind==='types'&&editing?.id&&['roleId','isClinical'].includes(field.key))continue;const value=values[field.key];if(field.type==='number'){if(value===''&&field.optional){result[field.key]=null;continue;}if(!/^\d+$/.test(String(value)))throw new Error(`Revisá ${field.label.toLowerCase()}.`);result[field.key]=Number(value);}else if(field.type==='date'){const date=clinicInstant(String(value));if(!date)throw new Error(`Revisá ${field.label.toLowerCase()}.`);result[field.key]=date;}else if(field.type==='bool')result[field.key]=Boolean(value);else {if(!String(value??'').trim()&&!field.optional)throw new Error(`Completá ${field.label.toLowerCase()}.`);result[field.key]=String(value??'').trim()||null;}}return result;}
 return <PetCareScreen><PetCareHeader title={form.title} subtitle="Cambios compartidos con toda la clínica" back/><PetCareCard><AppInput label="Buscar" value={search} onChangeText={setSearch}/><AppButton label="Buscar" onPress={()=>{setSubmitted(search.trim());setPage(1);}}/><AppButton label="Crear" disabled={kind==='products'&&!hasPermission('products.create')} onPress={()=>begin()}/></PetCareCard><QueryState {...query}/>{query.data&&(query.data.length?query.data.map(row=><PetCareCard key={row.id}><AppText variant="subtitle">{String(row.name)}</AppText>{row.isActive!==undefined&&<AppText>{row.isActive?'Activo':'Inactivo'}</AppText>}{kind==='products'&&<AppText>Físico: {String(row.stock)} · Reservado: {String(row.reservedStock)} · Disponible: {Number(row.stock)-Number(row.reservedStock)}</AppText>}<AppButton label="Editar" variant="secondary" onPress={()=>begin(row)}/></PetCareCard>):<PetCareEmptyState title="No hay registros en esta consulta"/>)}<AppButton label="Anterior" disabled={page===1} onPress={()=>setPage(p=>p-1)}/><AppButton label="Siguiente" disabled={!query.data||query.data.length<100} onPress={()=>setPage(p=>p+1)}/>
 {editing&&<PetCareCard><AppText variant="subtitle">{editing.id?'Editar':'Crear'} {form.title.toLowerCase()}</AppText><QueryState {...catalog}/>{form.fields.filter(f=>!f.permission||hasPermission(f.permission)).map(f=>f.type==='bool'?<SelectionRow key={f.key} label={f.label} checked={Boolean(values[f.key])} disabled={kind==='types'&&Boolean(editing.id)&&f.key==='isClinical'} onPress={()=>setValues(s=>({...s,[f.key]:!s[f.key]}))}/>:f.type==='select'?<PetCareCard key={f.key}><AppText>{f.label}</AppText>{f.optional&&<SelectionRow label="Sin asignar" checked={!values[f.key]} onPress={()=>setValues(s=>({...s,[f.key]:''}))}/>} {options(f.catalog).map(o=><SelectionRow key={o.id} radio label={o.name} checked={values[f.key]===o.id} disabled={kind==='types'&&Boolean(editing.id)} onPress={()=>setValues(s=>({...s,[f.key]:o.id}))}/>)}</PetCareCard>:<AppInput key={f.key} label={f.label} value={String(values[f.key]??'')} keyboardType={f.type==='number'?'number-pad':'default'} multiline={['description','requirements'].includes(f.key)} onChangeText={v=>setValues(s=>({...s,[f.key]:v}))}/>)}<FormNotice error message={error}/><AppButton label="Guardar" onPress={()=>{try{payload();setError(null);setConfirm(true);}catch(e){setError((e as Error).message);}}}/><AppButton label="Cerrar edición" variant="secondary" onPress={()=>setEditing(null)}/></PetCareCard>}
 <ConfirmModal visible={confirm} title="Guardar configuración" message="Los cambios se aplicarán a los datos reales y se reflejarán en los otros roles." confirmLabel="Guardar" onCancel={()=>setConfirm(false)} onConfirm={async()=>{await api.adminSave(kind,editing?.id||undefined,payload());setConfirm(false);setEditing(null);showToast('Configuración guardada','success');query.reload();catalog.reload();}}/></PetCareScreen>;
}
