/**
 * Listado y detalle de clientes para personal con permisos. Usa solicitudes autenticadas a /clinic/clients; el backend exige permisos separados para datos, turnos y reservas.
 */
import { useCallback,useState } from 'react';
import { router,useLocalSearchParams } from 'expo-router';
import { useAuth } from '../../hooks/useAuth';
import { useClinic } from '../../hooks/useClinic';
import { useClientQuery } from '../../hooks/useClientQuery';
import { PetCareScreen,PetCareHeader,PetCareCard,PetCareEmptyState,QueryState,statusLabel } from '../client/PetCareUI';
import { AppText } from '../ui/AppText';
import { AppButton } from '../ui/AppButton';
import { AppInput } from '../forms/AppInput';
export function ClientsScreen(){const {hasPermission}=useAuth();const api=useClinic();const [search,setSearch]=useState(''),[submitted,setSubmitted]=useState('');const query=useClientQuery(useCallback(()=>api.clients(submitted),[api,submitted]));return <PetCareScreen><PetCareHeader title="Clientes" subtitle="Información operativa autorizada" back/><AppInput label="Buscar nombre o email" value={search} onChangeText={setSearch}/><AppButton label="Buscar" onPress={()=>setSubmitted(search.trim())}/><QueryState {...query}/>{query.data&&(query.data.length?query.data.map(c=><PetCareCard key={c.id}><AppText variant="subtitle">{String(c.firstName)} {String(c.lastName)}</AppText><AppText>{String(c.email)}</AppText>{c.phone&&<AppText>{String(c.phone)}</AppText>}{hasPermission('appointments.view_all','reservations.view_all')&&<AppButton label="Mascotas, turnos y reservas" onPress={()=>router.push({pathname:'/secretary/client' as never,params:{id:c.id}})}/>}</PetCareCard>):<PetCareEmptyState title="No hay clientes en esta consulta"/>)}</PetCareScreen>;}
export function ClientScreen(){const {id}=useLocalSearchParams<{id:string}>();const api=useClinic();const query=useClientQuery(useCallback(()=>api.client(id),[api,id]));return <PetCareScreen><PetCareHeader title="Ficha operativa" back/><QueryState {...query}/>{query.data&&<><PetCareCard><AppText variant="subtitle">{String(query.data.client.firstName)} {String(query.data.client.lastName)}</AppText><AppText>{String(query.data.client.email)}</AppText>{query.data.client.phone&&<AppText>{String(query.data.client.phone)}</AppText>}</PetCareCard><AppText variant="subtitle">Mascotas</AppText>{query.data.pets.map(p=><PetCareCard key={p.id}><AppText>{String(p.name)}</AppText></PetCareCard>)}{!query.data.pets.length&&<PetCareEmptyState title="No hay mascotas registradas"/>}<AppText variant="subtitle">Turnos</AppText>{query.data.appointments.map(a=><PetCareCard key={a.id}><AppText>{String(a.petName)} · {String(a.service)}</AppText><AppText>{statusLabel(String(a.status))}</AppText></PetCareCard>)}{!query.data.appointments.length&&<PetCareEmptyState title="No hay turnos registrados"/>}<AppText variant="subtitle">Reservas</AppText>{query.data.reservations.map(r=><PetCareCard key={r.id}><AppText>#{r.id} · {statusLabel(String(r.status))}</AppText></PetCareCard>)}{!query.data.reservations.length&&<PetCareEmptyState title="No hay reservas registradas"/>}</>}</PetCareScreen>;}
