import { useCallback,useState } from 'react';
import { router,useLocalSearchParams } from 'expo-router';
import { useClinic } from '../../hooks/useClinic';
import { useAuth } from '../../hooks/useAuth';
import { useClientQuery } from '../../hooks/useClientQuery';
import { useAsyncAction } from '../../hooks/useAsyncAction';
import { useFeedback } from '../../contexts/FeedbackContext';
import { PetCareScreen,PetCareHeader,PetCareCard,PetCareEmptyState,PetImage,QueryState } from '../client/PetCareUI';
import { AppText } from '../ui/AppText';
import { AppButton } from '../ui/AppButton';
import { AppInput } from '../forms/AppInput';
import { FormNotice } from '../ui/FormNotice';
import { SelectionRow } from '../ui/SelectionRow';
import { ConfirmModal } from '../ui/ConfirmModal';
import { clinicInstant,clinicDateTime } from '../../utils/clinic-date';
export function PatientsScreen(){const {user}=useAuth();const base=user?.role==='VETERINARIAN'?'/vet':'/admin';const api=useClinic();const [search,setSearch]=useState(''),[submitted,setSubmitted]=useState('');const query=useClientQuery(useCallback(()=>api.patients(submitted),[api,submitted]));return <PetCareScreen><PetCareHeader title="Mis pacientes" back/><AppInput label="Buscar mascota / propietario autorizado" value={search} onChangeText={setSearch}/><AppButton label="Buscar" onPress={()=>setSubmitted(search.trim())}/><QueryState {...query}/>{query.data&&(query.data.length?query.data.map(p=><PetCareCard key={p.id}><AppText variant="subtitle">{String(p.name)}</AppText><AppText>{String(p.species)}</AppText>{p.ownerName&&<AppText>{String(p.ownerName)}</AppText>}{p.weightKg&&<AppText>Peso: {String(p.weightKg)} kg</AppText>}<AppButton label="Ficha clínica" onPress={()=>router.push({pathname:`${base}/patient` as never,params:{id:p.id}})}/></PetCareCard>):<PetCareEmptyState title="No tenés pacientes asignados en esta consulta"/>)}</PetCareScreen>;}
const recordKinds=[{kind:'medical-history',label:'Consultas',view:'medical_records.view',create:'medical_records.create'},{kind:'vaccines',label:'Vacunas',view:'vaccines.view',create:'vaccines.create'},{kind:'prescriptions',label:'Recetas',view:'prescriptions.view',create:'prescriptions.create'},{kind:'recommendations',label:'Recomendaciones',view:'medical_records.view',create:'recommendations.create'}];
export function PatientScreen(){const {id}=useLocalSearchParams<{id:string}>();const api=useClinic();const {user,hasPermission}=useAuth();const [kind,setKind]=useState(recordKinds.find(k=>hasPermission(k.view))?.kind??'');const details=useClientQuery(useCallback(()=>api.patient(id),[api,id]));const allowed=recordKinds.filter(k=>hasPermission(k.view));const query=useClientQuery(useCallback(()=>kind?api.records(id,kind):Promise.resolve(null),[api,id,kind]));return <PetCareScreen><PetCareHeader title="Ficha clínica" back/><QueryState {...details}/>{details.data&&<PetCareCard><PetImage uri={details.data.photoUrl?String(details.data.photoUrl):null}/><AppText variant="subtitle">{String(details.data.name)}</AppText><AppText>{String(details.data.species)}{details.data.breed?` · ${String(details.data.breed)}`:''}</AppText>{details.data.weightKg&&<AppText>Peso: {String(details.data.weightKg)} kg</AppText>}{details.data.birthDate&&<AppText>Nació: {String(details.data.birthDate).split('-').reverse().join('/')}</AppText>}{details.data.ownerName&&<AppText>Propietario: {String(details.data.ownerName)}</AppText>}</PetCareCard>}<PetCareCard>{allowed.map(k=><SelectionRow key={k.kind} radio label={k.label} checked={kind===k.kind} onPress={()=>setKind(k.kind)}/>)}</PetCareCard><QueryState {...query}/>{query.data&&(query.data.length?query.data.map(r=><PetCareCard key={r.id}><AppText variant="subtitle">{String(r.title)}</AppText><AppText>{clinicDateTime(String(r.occurredAt))}</AppText><AppText>{String(r.content)}</AppText>{r.reason&&<AppText>Motivo: {String(r.reason)}</AppText>}{r.diagnosis&&<AppText>Diagnóstico: {String(r.diagnosis)}</AppText>}{r.treatment&&<AppText>Tratamiento: {String(r.treatment)}</AppText>}{r.nextDueAt&&<AppText>Próximo control/dosis: {clinicDateTime(String(r.nextDueAt))}</AppText>}{r.validUntil&&<AppText>Vigencia: {clinicDateTime(String(r.validUntil))}</AppText>}</PetCareCard>):<PetCareEmptyState title="No hay registros para esta sección"/>)}{recordKinds.filter(k=>user?.role==='VETERINARIAN'&&hasPermission(k.create)).map(k=><AppButton key={k.kind} label={`Registrar ${k.label.toLowerCase()}`} onPress={()=>router.push({pathname:'/vet/record' as never,params:{id,kind:k.kind}})}/>)}</PetCareScreen>;}
export function ClinicalEditor(){const {id,kind}=useLocalSearchParams<{id:string;kind:string}>();const api=useClinic();const {hasPermission}=useAuth();const action=useAsyncAction();const {showToast}=useFeedback();const [values,setValues]=useState<Record<string,string>>({title:'',content:'',occurredAt:'',nextDueAt:'',validUntil:'',weightKg:'',reason:'',diagnosis:'',treatment:'',productId:'',consultationId:''});const [error,setError]=useState<string|null>(null),[confirm,setConfirm]=useState(false);
 // El catálogo de productos clínicos se consulta por el endpoint público real en RecordProductPicker.
 const consultations=useClientQuery(useCallback(()=>kind!=='medical-history'&&hasPermission('medical_records.view')?api.records(id,'medical-history'):Promise.resolve(null),[api,id,kind,hasPermission]));
 const change=(field:string,value:string)=>setValues(s=>({...s,[field]:value}));
 return <PetCareScreen><PetCareHeader title="Registrar información clínica" back/><PetCareCard><AppInput label="Título" value={values.title} onChangeText={v=>change('title',v)} maxLength={200}/><AppInput label="Contenido / indicaciones" multiline value={values.content} onChangeText={v=>change('content',v)} maxLength={20000}/><AppInput label="Fecha DD/MM/AAAA HH:mm (Argentina)" value={values.occurredAt} onChangeText={v=>change('occurredAt',v)}/><AppInput label="Próximo control/dosis DD/MM/AAAA HH:mm (opcional)" value={values.nextDueAt} onChangeText={v=>change('nextDueAt',v)}/>{kind==='medical-history'&&<><AppInput label="Peso kg (opcional)" keyboardType="decimal-pad" value={values.weightKg} onChangeText={v=>change('weightKg',v)}/><AppInput label="Motivo" multiline value={values.reason} onChangeText={v=>change('reason',v)}/>{hasPermission('medical_records.diagnose')&&<AppInput label="Diagnóstico" multiline value={values.diagnosis} onChangeText={v=>change('diagnosis',v)}/>} {hasPermission('medical_records.treat')&&<AppInput label="Tratamiento" multiline value={values.treatment} onChangeText={v=>change('treatment',v)}/>}</>}{kind==='prescriptions'&&<><AppInput label="Vigencia hasta DD/MM/AAAA HH:mm" value={values.validUntil} onChangeText={v=>change('validUntil',v)}/><RecordProductPicker selected={values.productId} onSelect={v=>change('productId',v)}/></>}{kind!=='medical-history'&&hasPermission('medical_records.view')&&<><QueryState {...consultations}/><AppText>Consulta asociada (opcional)</AppText><SelectionRow label="Sin consulta" checked={!values.consultationId} onPress={()=>change('consultationId','')}/>{consultations.data?.map(r=><SelectionRow key={r.id} label={String(r.title)} checked={values.consultationId===r.id} onPress={()=>change('consultationId',r.id)}/>)}</>}<FormNotice error message={error??action.error}/><AppButton label="Guardar registro" loading={action.loading} onPress={()=>{if(!values.title.trim()||!values.content.trim()||!clinicInstant(values.occurredAt)||values.nextDueAt&&!clinicInstant(values.nextDueAt)||values.validUntil&&!clinicInstant(values.validUntil)){setError('Completá título, contenido y fechas válidas.');return;}setError(null);setConfirm(true);}}/></PetCareCard><ConfirmModal visible={confirm} title="Guardar registro clínico" message="La información quedará asociada a la mascota y será visible para su propietario." confirmLabel="Guardar" onCancel={()=>setConfirm(false)} onConfirm={async()=>{await api.saveRecord(id,kind,{...values,occurredAt:clinicInstant(values.occurredAt),nextDueAt:values.nextDueAt?clinicInstant(values.nextDueAt):null,validUntil:values.validUntil?clinicInstant(values.validUntil):null,weightKg:values.weightKg?Number(values.weightKg.replace(',','.')):null,productId:values.productId||null,consultationId:values.consultationId||null});setConfirm(false);showToast('Registro guardado','success');router.back();}}/></PetCareScreen>;
}
function RecordProductPicker({selected,onSelect}:{selected:string;onSelect:(id:string)=>void}){const api=useClinic();const query=useClientQuery(api.products);return <><QueryState {...query}/><AppText muted>Producto asociado (opcional). La receta no genera una reserva.</AppText><SelectionRow label="Sin producto" checked={!selected} onPress={()=>onSelect('')}/>{query.data?.map(p=><SelectionRow key={p.id} label={p.name} checked={selected===p.id} onPress={()=>onSelect(p.id)}/>)}</>;}
