import { useCallback,useState } from 'react';
import { router,useLocalSearchParams } from 'expo-router';
import { useClinic } from '../../hooks/useClinic';
import { useAuth } from '../../hooks/useAuth';
import { useClientQuery } from '../../hooks/useClientQuery';
import { PetCareScreen,PetCareHeader,PetCareCard,PetCareEmptyState,QueryState,statusLabel,money } from '../client/PetCareUI';
import { AppText } from '../ui/AppText';
import { AppButton } from '../ui/AppButton';
import { SelectionRow } from '../ui/SelectionRow';
import { ConfirmModal } from '../ui/ConfirmModal';
import { clinicDateTime } from '../../utils/clinic-date';
import { useFeedback } from '../../contexts/FeedbackContext';
export function ReservationsScreen(){const api=useClinic();const {user}=useAuth();const [status,setStatus]=useState('');const [page,setPage]=useState(1);const query=useClientQuery(useCallback(()=>api.reservations({status,page:String(page)}),[api,status,page]));const base=user?.role==='CLIENT'?'/client':user?.role==='SECRETARY'?'/secretary':'/admin';return <PetCareScreen><PetCareHeader title={user?.role==='CLIENT'?'Mis reservas':'Reservas para retiro'} subtitle="PetCare no procesa pagos" back/><PetCareCard>{['','PLACED','CONFIRMED','PROCESSING','READY','COMPLETED','CANCELLED'].map(s=><SelectionRow key={s} label={s?statusLabel(s):'Todas'} checked={s===status} onPress={()=>{setStatus(s);setPage(1);}}/>)}</PetCareCard><QueryState {...query}/>{query.data&&(query.data.length?query.data.map(r=><PetCareCard key={r.id}><AppText variant="subtitle">Reserva #{r.id}</AppText>{r.clientName&&<AppText>{String(r.clientName)}</AppText>}<AppText>{statusLabel(String(r.status))}</AppText><AppText>{clinicDateTime(String(r.createdAt))}</AppText><AppText>Importe informativo: {money(Number(r.totalCents))}</AppText><AppButton label="Ver reserva" onPress={()=>router.push({pathname:`${base}/reservation` as never,params:{id:r.id}})}/></PetCareCard>):<PetCareEmptyState title="No hay reservas en esta consulta" icon="bag-handle-outline"/>)}<AppButton label="Anterior" disabled={page===1} onPress={()=>setPage(p=>p-1)}/><AppButton label="Siguiente" disabled={!query.data||query.data.length<100} onPress={()=>setPage(p=>p+1)}/></PetCareScreen>;}
export function ReservationScreen(){const {id}=useLocalSearchParams<{id:string}>();const api=useClinic();const {hasPermission}=useAuth();const query=useClientQuery(useCallback(()=>api.reservation(id),[api,id]));const [next,setNext]=useState<string|null>(null);const {showToast}=useFeedback();const transitions:Record<string,string[]>={PLACED:['CONFIRMED','CANCELLED'],CONFIRMED:['PROCESSING','CANCELLED'],PROCESSING:['READY','CANCELLED'],READY:['COMPLETED','CANCELLED']};return <PetCareScreen><PetCareHeader title={`Reserva #${id}`} back/><QueryState {...query}/>{query.data&&<><PetCareCard><AppText variant="subtitle">{statusLabel(String(query.data.status))}</AppText><AppText>Retiro y gestión en la veterinaria. Sin pago online.</AppText>{query.data.clientName&&<AppText>{String(query.data.clientName)}</AppText>}{query.data.phone&&<AppText>Contacto: {String(query.data.phone)}</AppText>}<AppText>Importe informativo: {money(Number(query.data.totalCents))}</AppText></PetCareCard>{query.data.items?.map(item=><PetCareCard key={String(item.productId)}><AppText variant="subtitle">{String(item.name)}</AppText><AppText>Cantidad: {String(item.quantity)}</AppText>{item.petName&&<AppText>Mascota: {String(item.petName)}</AppText>}{item.prescriptionId&&<AppText>Receta asociada: #{String(item.prescriptionId)}</AppText>}</PetCareCard>)}{hasPermission('reservations.manage')&&(transitions[String(query.data.status)]??[]).map(s=><AppButton key={s} label={s==='COMPLETED'?'Marcar retirada':s==='PROCESSING'?'Preparar':statusLabel(s)} onPress={()=>setNext(s)}/>)}</>}<ConfirmModal visible={Boolean(next)} title="Actualizar reserva" message={next==='CANCELLED'?'Se cancelará la reserva y se liberarán sus unidades.':next==='COMPLETED'?'Se registrará el retiro y se descontarán las unidades del stock físico.':'El cliente verá el estado actualizado.'} destructive={next==='CANCELLED'} confirmLabel="Confirmar" onCancel={()=>setNext(null)} onConfirm={async()=>{await api.changeReservation(id,next!);setNext(null);showToast('Reserva actualizada','success');query.reload();}}/></PetCareScreen>;}
