import { Router } from 'express';
import { authenticate } from '../middlewares/auth.middleware';
import { requireRole } from '../middlewares/permission.middleware';
import { createAuthRateLimiter } from '../middlewares/auth-rate-limit.middleware';
import { clientHandler as handle } from '../controllers/client.controller';
export const clientRouter=Router();
clientRouter.use(authenticate,requireRole('CLIENT'));
clientRouter.use((_req,res,next)=>{res.setHeader('Cache-Control','no-store');next();});
clientRouter.get('/home',handle('home'));
clientRouter.get('/pets/catalog',handle('pet-catalog'));
clientRouter.get('/pets',handle('pets'));
clientRouter.post('/pets',handle('create-pet',201));
clientRouter.get('/pets/:id',handle('pet'));
clientRouter.put('/pets/:id',handle('update-pet'));
clientRouter.patch('/pets/:id/deactivate',handle('deactivate-pet'));
clientRouter.get('/appointments/catalog',handle('appointment-catalog'));
clientRouter.get('/appointments/slots',handle('slots'));
clientRouter.get('/appointments',handle('appointments'));
clientRouter.post('/appointments',handle('create-appointment',201));
clientRouter.get('/clinical/:kind',handle('clinical'));
clientRouter.get('/store/categories',handle('categories'));
clientRouter.get('/store/products',handle('products'));
clientRouter.get('/store/products/:id',handle('product'));
clientRouter.get('/cart',handle('cart'));
clientRouter.put('/cart/:id',handle('cart-update'));
clientRouter.get('/orders',handle('orders'));
clientRouter.post('/orders',handle('checkout',201));
clientRouter.get('/orders/:id',handle('order'));
clientRouter.get('/notifications',handle('notifications'));
clientRouter.patch('/notifications/:id/read',handle('notification-read'));
clientRouter.patch('/profile',handle('profile-update'));
clientRouter.put('/profile/password',createAuthRateLimiter(),handle('password-update'));
